### PR TITLE
Gulp 4 Upgrade

### PR DESCRIPTION
**Pull request by mread1208**
#1 Updated the gulp package to use Gulp v4.  Updated the gulpfile.js to use the new Gulp 4 syntax.

### CODE REVIEW

**Comment by esausilva** [comment]
Thank you for taking the time to work on this. Just one thing before I merge. When I edit `index.html`, the site reloads fine, however when I make a second edit (or any subsequent edits), the site does not reload and that is because the site is not getting re-built. The CSS reloads fine with every change.

**Comment by mread1208** [comment]
Just pushed some updates!  Sorry, I tested it once, but not concurrent reloads.  Everything should be working now with the default task.

I'm not sure how to test if the deploy to GitHub pages is working or not. I did update the syntax to use Gulp 4 and ran the task without any errors, but not sure if it actually deploys out or not.

**Comment by esausilva** [comment]
Thank you! I appreciate it 😁

**Comment by esausilva** [comment]
The deploy task wasn't working, but is fixed now ([https://esausilva.github.io/jekyll-gulp-boilerplate/](https://esausilva.github.io/jekyll-gulp-boilerplate/)). Thanks

**Pull request merged**
